import * as React from 'react';
import { ItemView, WorkspaceLeaf, Notice } from 'obsidian';
import { Root, createRoot } from 'react-dom/client';
import { DatabaseManager } from './database';
import { AssetManifest } from './types';

export const VIEW_TYPE_DASHBOARD = 'asset-tracker-dashboard';

export class DashboardView extends ItemView {
	root: Root | null = null;
	database: DatabaseManager;

	constructor(leaf: WorkspaceLeaf, database: DatabaseManager) {
		super(leaf);
		this.database = database;
	}

	getViewType(): string {
		return VIEW_TYPE_DASHBOARD;
	}

	getDisplayText(): string {
		return 'Asset Tracker Dashboard';
	}

	getIcon(): string {
		return 'database';
	}

	async onOpen() {
		const container = this.containerEl.children[1];
		container.empty();
		
		this.root = createRoot(container);
		this.root.render(
			<Dashboard 
				database={this.database}
				onImport={(manifest) => this.handleImport(manifest)}
			/>
		);
	}

	async onClose() {
		if (this.root) {
			this.root.unmount();
		}
	}

	async handleImport(manifest: AssetManifest): Promise<void> {
		try {
			await this.database.importManifest(manifest);
			new Notice(`Successfully imported ${manifest.pack_name}!`);
			
			// Refresh the view
			if (this.root) {
				this.root.render(
					<Dashboard 
						database={this.database}
						onImport={(manifest) => this.handleImport(manifest)}
					/>
				);
			}
		} catch (error) {
			console.error('Import error:', error);
			new Notice('Failed to import manifest: ' + error.message);
		}
	}
}

interface DashboardProps {
	database: DatabaseManager;
	onImport: (manifest: AssetManifest) => Promise<void>;
}

function Dashboard({ database, onImport }: DashboardProps) {
	const [assetCount, setAssetCount] = React.useState<number>(0);
	const [packCount, setPackCount] = React.useState<number>(0);
	const [isImporting, setIsImporting] = React.useState(false);

	React.useEffect(() => {
		updateStats();
	}, []);

	const updateStats = () => {
		try {
			const count = database.getAssetCount();
			const packs = database.getAllPacks();
			setAssetCount(count);
			setPackCount(packs.length);
		} catch (error) {
			console.error('Error getting stats:', error);
		}
	};

	const handleFileSelect = async (event: React.ChangeEvent<HTMLInputElement>) => {
		const file = event.target.files?.[0];
		if (!file) return;

		setIsImporting(true);

		try {
			const text = await file.text();
			const manifest: AssetManifest = JSON.parse(text);
			
			// Basic validation
			if (!manifest.pack_id || !manifest.pack_name || !manifest.assets) {
				throw new Error('Invalid manifest format');
			}

			await onImport(manifest);
			updateStats();
		} catch (error) {
			console.error('File processing error:', error);
			new Notice('Error processing file: ' + error.message);
		} finally {
			setIsImporting(false);
			// Reset file input
			event.target.value = '';
		}
	};

	return (
		<div style={{ padding: '20px' }}>
			<h2>Asset Tracker Dashboard</h2>
			
			<div style={{ 
				display: 'grid', 
				gridTemplateColumns: '1fr 1fr', 
				gap: '20px',
				marginBottom: '30px'
			}}>
				<StatCard title="Total Packs" value={packCount} />
				<StatCard title="Total Assets" value={assetCount} />
			</div>

			<div style={{ marginBottom: '30px' }}>
				<h3>Import Manifest</h3>
				<p style={{ color: 'var(--text-muted)', marginBottom: '10px' }}>
					Select a JSON manifest file generated by the ingestion script.
				</p>
				
				<label 
					htmlFor="file-input"
					style={{
						display: 'inline-block',
						padding: '10px 20px',
						backgroundColor: 'var(--interactive-accent)',
						color: 'var(--text-on-accent)',
						borderRadius: '5px',
						cursor: isImporting ? 'not-allowed' : 'pointer',
						opacity: isImporting ? 0.5 : 1
					}}
				>
					{isImporting ? 'Importing...' : 'Choose Manifest File'}
				</label>
				<input
					id="file-input"
					type="file"
					accept=".json"
					onChange={handleFileSelect}
					disabled={isImporting}
					style={{ display: 'none' }}
				/>
			</div>

			<div>
				<h3>Database Status</h3>
				<TestQuery database={database} />
			</div>
		</div>
	);
}

function StatCard({ title, value }: { title: string; value: number }) {
	return (
		<div style={{
			padding: '20px',
			backgroundColor: 'var(--background-secondary)',
			borderRadius: '8px',
			textAlign: 'center'
		}}>
			<div style={{ 
				fontSize: '32px', 
				fontWeight: 'bold',
				marginBottom: '8px'
			}}>
				{value}
			</div>
			<div style={{ color: 'var(--text-muted)' }}>
				{title}
			</div>
		</div>
	);
}

function TestQuery({ database }: { database: DatabaseManager }) {
	const [result, setResult] = React.useState<string>('');

	const runTest = () => {
		try {
			const count = database.getAssetCount();
			setResult(`✓ Database query successful: ${count} assets in database`);
		} catch (error) {
			setResult(`✗ Query failed: ${error.message}`);
		}
	};

	return (
		<div style={{
			padding: '15px',
			backgroundColor: 'var(--background-secondary)',
			borderRadius: '8px'
		}}>
			<button
				onClick={runTest}
				style={{
					padding: '8px 16px',
					backgroundColor: 'var(--interactive-accent)',
					color: 'var(--text-on-accent)',
					border: 'none',
					borderRadius: '4px',
					cursor: 'pointer',
					marginBottom: '10px'
				}}
			>
				Run Test Query
			</button>
			
			{result && (
				<div style={{ 
					marginTop: '10px',
					fontFamily: 'monospace',
					color: result.startsWith('✓') ? 'var(--text-success)' : 'var(--text-error)'
				}}>
					{result}
				</div>
			)}
		</div>
	);
}
